RedisExchangeAPI.WEB/Models/ErrorViewModel.cs
namespace RedisExchangeAPI.WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RedisExchangeAPI.WEB/Controllers/HashTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.WEB.Services;
using StackExchange.Redis;

namespace RedisExchangeAPI.WEB.Controllers
{
    public class HashTypeController : Controller
    {
        private readonly RedisService _redisService;
        private string listKey = "dictionary";

        public HashTypeController(RedisService redisService)
        {
            _redisService = redisService;
        }

        public IActionResult Index()
        {
            Dictionary<string,string>list= new Dictionary<string,string>();
            if(GetDb().KeyExists(listKey))
            {
                foreach (var item in GetDb().HashGetAll(listKey).ToList())
                {
                    list.Add(item.Name,item.Value);
                }
            }
            return View(list);
        }
        public IActionResult DeleteItem(string name)
        {
            GetDb().HashDelete(listKey, name);
            return RedirectToAction("Index");
        }

        public IActionResult Add(string key,string val)
        {
            GetDb().HashSet(listKey, key, val);
            return RedirectToAction("Index");
        }
        public IDatabase GetDb()
        {
            return _redisService.GetDb(1);
        }
    }
}

RedisExchangeAPI.WEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.WEB.Models;
using System.Diagnostics;

namespace RedisExchangeAPI.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RedisExchangeAPI.WEB/Controllers/ListTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.WEB.Services;
using StackExchange.Redis;

namespace RedisExchangeAPI.WEB.Controllers
{
    public class ListTypeController : Controller
    {
        private readonly RedisService _redisService;
        private string listKey = "names";
        public ListTypeController(RedisService redisService)
        {
            _redisService = redisService;
        }

        public IActionResult Index()
        {
            List<string> namesList = new List<string>();

            var db = GetDb();
            if (db.KeyExists(listKey))
            {
                foreach (var item in db.ListRange(listKey).ToList())
                {
                    namesList.Add(item.ToString());
                };
            }
            return View(namesList);
        }
        [HttpPost]
        public IActionResult Add(string name)
        {
            GetDb().ListRightPush(listKey, name);
            return View();
        }        
        public IActionResult DeleteItem(string name)
        {
            GetDb().ListRemove(listKey, name);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteFirsItem()
        {
            GetDb().ListLeftPop(listKey);
            return RedirectToAction("Index");
        }
        private IDatabase GetDb()
        {
            return _redisService.GetDb(1);
        }
    }
}

RedisExchangeAPI.WEB/Controllers/SetTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.WEB.Services;
using StackExchange.Redis;

namespace RedisExchangeAPI.WEB.Controllers
{
    public class SetTypeController : Controller
    {
        private readonly RedisService _redisService;
        private string listKey = "hashnames";

        public SetTypeController(RedisService redisService)
        {
            _redisService = redisService;
        }
        public IActionResult DeleteItem(string name)
        {
            GetDb().SetRemove(listKey, name);
            return RedirectToAction("Index");
        }
        public IActionResult Index()
        {
            HashSet<string> keys = new HashSet<string>();
            if(GetDb().KeyExists(listKey))
            {
                foreach (var item in GetDb().SetMembers(listKey).ToList())
                {
                    keys.Add(item.ToString());

                }
            }
           
            return View(keys);
        }
        [HttpPost]
        public IActionResult Add(string name)
        {
            if(!GetDb().KeyExists(listKey))
            {

            GetDb().KeyExpire(listKey,DateTime.Now.AddMinutes(5));
     
            }
            GetDb().SetAdd(listKey, name);
            return RedirectToAction("Index");
        }
        private IDatabase GetDb()
        {
            return _redisService.GetDb(2);
        }
    }
}

RedisExchangeAPI.WEB/Controllers/SortedTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.WEB.Services;
using StackExchange.Redis;

namespace RedisExchangeAPI.WEB.Controllers
{
    public class SortedTypeController : Controller
    {
        private readonly RedisService _redisService;
        private string listKey = "sortedsetnames";
        public SortedTypeController(RedisService redisService)
        {
            _redisService = redisService;
        }

       
        public IActionResult Index()
        {
            HashSet<string> keys = new HashSet<string>();

            if(GetDb().KeyExists(listKey))
            {
                foreach (var item in GetDb().SortedSetScan(listKey).ToList())
                {
                    keys.Add(item.ToString());
                };

                foreach (var item in GetDb().SortedSetRangeByRank(listKey, order: Order.Ascending).ToList())
                {
                    keys.Add(item.ToString());
                }
            }
            return View(keys);
        }
        public IActionResult DeleteItem(string name)
        {
            GetDb().SortedSetRemove(listKey, name);
            return RedirectToAction("Index");
        }


        public IActionResult Add(string name,int score)
        {
            GetDb().KeyExpire(listKey, DateTime.Now.AddMinutes(1));
            GetDb().SortedSetAdd(listKey,name,score);
            return RedirectToAction("Index");
        }
        public IDatabase GetDb()
        {
            return _redisService.GetDb(1);
        }
    }
}

RedisExchangeAPI.WEB/Controllers/StringTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.WEB.Services;
using StackExchange.Redis;

namespace RedisExchangeAPI.WEB.Controllers
{
    public class StringTypeController : Controller
    {
        private readonly RedisService _redisService;
        public StringTypeController(RedisService redisService)
        {
            _redisService = redisService;
        }

        public IActionResult Index()
        {
            var db = _redisService.GetDb(0);
            db.StringSet("name", "umut");
            db.StringSet("ziyaretci", 100);
            return View();
        }

        public IActionResult Show()
        {
            var db = _redisService.GetDb(0);
            
            var value =db.StringGet("name");

            var range = db.StringGetRange("name", 0, 3);//0dan karakterden 3 indise kadar alır
            var length = db.StringLength("name");//uzunluğu alır
            db.StringIncrement("ziyaretci", 1);//degeri bir artırır

            var count = db.StringDecrement("ziyaretci", 1);//degeri bir azaltır
            if(value.HasValue)
            {
                ViewBag.value = value;
            }
            return View();
        }
    }
}

RedisExchangeAPI.WEB/Views/HashType/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Dictionary<string,string>


<form method="post" asp-action="Add" asp-controller="HashType" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <input type="text" name="value" />
    <button type="submit">Kaydet</button>
</form>

@foreach (var item in Model)
{
    <li>@item.Key > @item.Value</li>
    <li><a href="/HashType/Delete/@item.Key"></a></li>
}

RedisExchangeAPI.WEB/Views/ListType/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

RedisExchangeAPI.WEB/Views/ListType/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<string>

<form method="post" asp-action="Add" asp-controller="ListType" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <button type="submit">Kaydet</button>
</form>

@foreach(var item in Model)
{
    <li>@item</li>
    <li><a href="/ListType/Delete/@item"></a></li>
}

RedisExchangeAPI.WEB/Views/SetType/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model HashSet<string>


<form method="post" asp-action="Add" asp-controller="SetType" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <button type="submit">Kaydet</button>
</form>

@foreach (var item in Model)
{
    <li>@item</li>
    <li><a href="/SetType/Delete/@item"></a></li>
}

RedisExchangeAPI.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RedisExchangeAPI.WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RedisExchangeAPI.WEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RedisExchangeAPI.WEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RedisExchangeAPI.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RedisExchangeAPI.WEB/Views/SortedType/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model HashSet<string>


<form method="post" asp-action="Add" asp-controller="SortedType" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <input type="text" name="score" />
    <button type="submit">Kaydet</button>
</form>

@foreach (var item in Model)
{
    <li>@item</li>
    <li><a href="/SortedType/Delete/@item"></a></li>
}

RedisExchangeAPI.WEB/Views/StringType/Show.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    var deger = ViewBag.value;
}

<h1>@deger</h1>